rating:
  start: 1000
  kFactorBase: 32
  kFactorSoloBonus: 4
  kFactorUnderdogBonus: 8
  mismatchWaitSeconds: 45

queue:
  searchIntervalTicks: 60

match:
  allowCommandsWhileInMatch: false
  blockedCommands:
    - "/fly"
  restoreFlightAfterMatch: true
  disableFriendlyFire: true
  graceSecondsOnStart: 3

weeklyReset:
  enabled: true
  resetDayOfWeek: 1
  resetHour: 0
  resetMinute: 0
  distributeRewardsOnLogin: true

tiers:
  - name: BRONZE
    min: 0
  - name: SILVER
    min: 900
  - name: GOLD
    min: 1100
  - name: PLATINUM
    min: 1300
  - name: DIAMOND
    min: 1500
  - name: MASTER
    min: 1700
