name: PvPCompetition
main: com.minkang.ultimate.pvpmm.Main
version: 1.0.8
api-version: 1.16
author: minkang
commands:
  경쟁전:
    usage: /경쟁전
    description: PvP 경쟁전 시스템
    aliases: [pvpmm, pvpmatch]
permissions:
  pvpmm.admin:
    default: op
  pvpmm.user:
    default: true
