name: PvPCompetition
main: com.minkang.ultimate.pvpmm.Main
version: 1.0.3
api-version: 1.16
author: minkang
commands:
  경쟁전:
    usage: /경쟁전
    description: PvP 경쟁전 시스템
    aliases: [pvpmm, pvpmatch]
permissions:
  pvpmm.admin:
    default: op
    description: 경쟁전 관리자 권한
  pvpmm.user:
    default: true
    description: 경쟁전 일반 사용자
