name: Build PvPCompetition

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: PvPCompetition-${{ github.run_number }}
          path: |
            target/*.jar
          if-no-files-found: error
